name: Bump version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    name: Bump version

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Bump version
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"

          npm version "0.1.$GITHUB_RUN_NUMBER" --git-tag-version false

          git commit -a -m 'bump version'
          git push
