name: Typecheck

on: push

jobs:
  typecheck:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node 16
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn

      - name: Check types
        run: yarn tsc
